// Common events
export const COMMON_RESET_STATE = 'COMMON_RESET_STATE'

export const TOUCH_DEVICE = 'TOUCH_DEVICE'

// Header for XS devices
export const HEADER_SET_BUTTON = 'HEADER_SET_BUTTON'
export const HEADER_UNSET_BUTTON = 'HEADER_UNSET_BUTTON'
export const HEADER_SET_HEADING = 'HEADER_SET_HEADING'
export const HEADER_UNSET_HEADING = 'HEADER_UNSET_HEADING'
export const HEADER_HIDE_HEADING = 'HEADER_HIDE_HEADING'
export const HEADER_HEADING_ICON = 'HEADER_HEADING_ICON'
export const HEADER_HEADING_FULL_ROW = 'HEADER_HEADING_FULL_ROW'
export const HEADER_SHOW_LEFT_BUTTON = 'HEADER_SHOW_LEFT_BUTTON'
export const HEADER_HIDE_LEFT_BUTTON = 'HEADER_HIDE_LEFT_BUTTON'
export const HEADER_SHOW_RIGHT_BUTTON = 'HEADER_SHOW_RIGHT_BUTTON'
export const HEADER_HIDE_RIGHT_BUTTON = 'HEADER_HIDE_RIGHT_BUTTON'
export const HEADER_SET_CUSTOM_CLASS = 'HEADER_SET_CUSTOM_CLASS'
export const HEADER_UNSET_CUSTOM_CLASS = 'HEADER_UNSET_CUSTOM_CLASS'
export const HEADER_SHOW_HAMBURGER = 'HEADER_SHOW_HAMBURGER'
export const HEADER_HIDE_HAMBURGER = 'HEADER_HIDE_HAMBURGER'
export const HEADER_SET_INFO_TEXT = 'HEADER_SET_INFO_TEXT'
export const HEADER_RESET_INFO_TEXT = 'HEADER_RESET_INFO_TEXT'
export const HEADER_ADD_TAB = 'HEADER_ADD_TAB'
export const HEADER_CLEAR_TABS = 'HEADER_CLEAR_TABS'

// Bottom navigation for XS devices
export const BOTTOM_NAVIGATION_ADD_ITEM = 'BOTTOM_NAVIGATION_ADD_ITEM'
export const BOTTOM_NAVIGATION_SHOW = 'BOTTOM_NAVIGATION_SHOW'
export const BOTTOM_NAVIGATION_HIDE = 'BOTTOM_NAVIGATION_HIDE'

// Theme
export const WINDOW_SIZE = 'WINDOW_SIZE'
export const WINDOW_HEIGHT = 'WINDOW_HEIGHT'
export const BODY_MARGIN = 'BODY_MARGIN'

// Account
export const ACCOUNT_USERNAME = 'ACCOUNT_USERNAME'
export const ACCOUNT_EMAIL = 'ACCOUNT_EMAIL'

// Menu
export const MENU_COLLAPSED = 'MENU_COLLAPSED'
