// Common events
export const COMMON_RESET_STATE = 'COMMON_RESET_STATE'

// Header for XS devices
export const HEADER_SET_BUTTON = 'HEADER_SET_BUTTON'
export const HEADER_UNSET_BUTTON = 'HEADER_UNSET_BUTTON'
export const HEADER_SET_HEADING = 'HEADER_SET_HEADING'
export const HEADER_UNSET_HEADING = 'HEADER_UNSET_HEADING'
export const HEADER_SHOW_RIGHT_BUTTON = 'HEADER_SHOW_RIGHT_BUTTON'
export const HEADER_HIDE_RIGHT_BUTTON = 'HEADER_HIDE_RIGHT_BUTTON'
export const HEADER_SET_CUSTOM_CLASS = 'HEADER_SET_CUSTOM_CLASS'
export const HEADER_UNSET_CUSTOM_CLASS = 'HEADER_UNSET_CUSTOM_CLASS'
export const HEADER_SHOW_SHADOW = 'HEADER_SHOW_SHADOW'
export const HEADER_HIDE_SHADOW = 'HEADER_HIDE_SHADOW'

// Theme
export const WINDOW_SIZE = 'WINDOW_SIZE'

// Account
export const ACCOUNT_USERNAME = 'ACCOUNT_USERNAME'
export const ACCOUNT_EMAIL = 'ACCOUNT_EMAIL'

// Menu
export const MENU_COLLAPSED = 'MENU_COLLAPSED'
